/**
 * serialise.js — Campaign object → YAML text per-file.
 *
 * Pure module: no DOM access. Accesses globalThis.jsyaml (same convention as
 * campaign.js — js-yaml is loaded as a non-module <script> tag).
 *
 * Single export: serialiseCampaign(campaign, originalFileMap)
 */

/**
 * Serialise a campaign object back to a map of filename → YAML text.
 *
 * metadata always goes to metadata.yaml.
 * All scenes are written to a single scenes.yaml unless the session started
 * with multiple scene files (in which case the original file assignment is
 * preserved — scenes added in Visual mode go into a new 'new_scenes.yaml').
 *
 * items: block is appended to the file that originally contained it, or to
 * items.yaml if no items were present on load.
 *
 * recipes: block is appended to the file that originally contained it, or to
 * recipes.yaml if no recipes were present on load.
 *
 * attributes: block is appended to the file that originally contained it (if
 * that file is not metadata.yaml), or appended to metadata.yaml by default.
 *
 * @param {{ metadata: object, scenes: object, items: object, recipes: Array, assets: object }} campaign
 * @param {Map<string, string>|null} originalFileMap  previous file map for provenance; null = single-file mode
 * @returns {Map<string, string>}  filename → YAML text
 */
export function serialiseCampaign(campaign, originalFileMap) {
  const yaml = globalThis.jsyaml;
  if (!yaml) throw new Error('js-yaml not loaded');

  const dumpOpts = { indent: 2, lineWidth: 120, schema: yaml.DEFAULT_SCHEMA };
  const header = '# Generated by Campaign Editor\n';

  const metadata   = campaign.metadata   ?? {};
  const scenes     = campaign.scenes     ?? {};
  const items      = campaign.items      ?? {};
  const recipes    = campaign.recipes    ?? [];
  const assets     = campaign.assets     ?? {};
  const attributes = campaign.attributes ?? {};

  // ── 1. Serialise metadata.yaml ──────────────────────────────────────────────

  const metaObj = buildMetadataObj(metadata);
  let metaText = header + yaml.dump({ metadata: metaObj }, dumpOpts);
  // attributes appended to metaText below, after provenance is determined

  // ── 2. Determine scene→file assignment ──────────────────────────────────────

  // sceneSourceFile: sceneId → filename (from original file map if available)
  const sceneSourceFile = new Map();

  if (originalFileMap && originalFileMap.size > 0) {
    for (const [filename, text] of originalFileMap) {
      if (filename === 'metadata.yaml') continue;
      // Scan for top-level scene keys under a 'scenes:' block.
      // Matches lines like "  scene_id:" (2-space indent, word chars + hyphen/underscore).
      const re = /^  ([\w][\w_-]*):/gm;
      let m;
      while ((m = re.exec(text)) !== null) {
        if (!sceneSourceFile.has(m[1])) {
          sceneSourceFile.set(m[1], filename);
        }
      }
    }
  }

  // ── 3. Determine items→file assignment ──────────────────────────────────────

  let itemsFile = 'items.yaml'; // default (separate from scenes)
  if (originalFileMap && originalFileMap.size > 0) {
    for (const [filename, text] of originalFileMap) {
      if (filename === 'metadata.yaml') continue;
      if (/^items:/m.test(text)) {
        itemsFile = filename;
        break;
      }
    }
  }

  // ── 3b. Determine recipes→file assignment ───────────────────────────────────

  let recipesFile = 'recipes.yaml'; // default
  if (originalFileMap && originalFileMap.size > 0) {
    for (const [filename, text] of originalFileMap) {
      if (filename === 'metadata.yaml') continue;
      if (/^recipes:/m.test(text)) { recipesFile = filename; break; }
    }
  }

  // ── 3c. Determine assets→file assignment ────────────────────────────────────

  let assetsFile = 'assets.yaml'; // default
  if (originalFileMap && originalFileMap.size > 0) {
    for (const [filename, text] of originalFileMap) {
      if (filename === 'metadata.yaml') continue;
      if (/^assets:/m.test(text)) { assetsFile = filename; break; }
    }
  }

  // ── 3d. Determine attributes→file assignment ────────────────────────────────
  // null = append to metadata.yaml (default); otherwise a named file

  let attrsFile = null;
  if (originalFileMap && originalFileMap.size > 0) {
    for (const [filename, text] of originalFileMap) {
      if (filename === 'metadata.yaml') continue;
      if (/^attributes:/m.test(text)) { attrsFile = filename; break; }
    }
  }

  const attrsObj = buildAttributesObj(attributes);
  if (attrsObj && !attrsFile) {
    metaText += '\n' + yaml.dump({ attributes: attrsObj }, dumpOpts);
  }

  // ── 4. Group scenes by output file ──────────────────────────────────────────

  // scenesByFile: filename → { sceneId: sceneData }
  const scenesByFile = new Map();

  for (const [sceneId, sceneData] of Object.entries(scenes)) {
    const file = sceneSourceFile.get(sceneId) ?? 'scenes.yaml';
    // Scenes added in Visual mode that weren't in the original file map get
    // placed into new_scenes.yaml (only when originalFileMap is non-null).
    const targetFile = (originalFileMap && originalFileMap.size > 0 && !sceneSourceFile.has(sceneId))
      ? 'new_scenes.yaml'
      : file;

    if (!scenesByFile.has(targetFile)) scenesByFile.set(targetFile, {});
    scenesByFile.get(targetFile)[sceneId] = sceneData;
  }

  // Ensure scenes.yaml always exists even if empty (so Code mode has something to show)
  if (!scenesByFile.has('scenes.yaml')) scenesByFile.set('scenes.yaml', {});

  // ── 5. Items serialisation helper ───────────────────────────────────────────

  function buildItemsObj() {
    const itemsOut = {};
    for (const [name, item] of Object.entries(items)) {
      const desc = typeof item === 'string' ? item : (item?.description ?? '');
      const affects = item?.affect_attributes ?? {};
      const icon = item?.icon ?? null;
      if (Object.keys(affects).length > 0 || icon) {
        const entry = { description: desc, affect_attributes: affects };
        if (icon) entry.icon = icon;
        itemsOut[name] = entry;
      } else {
        itemsOut[name] = desc;
      }
    }
    return itemsOut;
  }

  // ── 6. Serialise each scene file ────────────────────────────────────────────

  const result = new Map();
  result.set('metadata.yaml', metaText);

  for (const [filename, fileScenes] of scenesByFile) {
    const scenesObj = {};
    for (const [sceneId, sceneData] of Object.entries(fileScenes)) {
      scenesObj[sceneId] = buildSceneObj(sceneData);
    }

    let fileContent = header;
    fileContent += yaml.dump({ scenes: scenesObj }, dumpOpts);

    // Append items block to the designated file
    if (filename === itemsFile && Object.keys(items).length > 0) {
      fileContent += '\n' + yaml.dump({ items: buildItemsObj() }, dumpOpts);
    }

    // Append recipes block to the designated file
    if (filename === recipesFile && recipes.length > 0) {
      fileContent += '\n' + yaml.dump({ recipes: recipes.map(buildRecipeObj) }, dumpOpts);
    }

    // Append assets block to the designated file
    const assetsOut = buildAssetsObj(assets);
    if (filename === assetsFile && assetsOut) {
      fileContent += '\n' + yaml.dump({ assets: assetsOut }, dumpOpts);
    }

    // Append attributes block to the designated file
    if (attrsFile && filename === attrsFile && attrsObj) {
      fileContent += '\n' + yaml.dump({ attributes: attrsObj }, dumpOpts);
    }

    result.set(filename, fileContent);
  }

  // If items are assigned to a file that had no scenes, create standalone items file.
  if (!result.has(itemsFile) && Object.keys(items).length > 0) {
    let fileContent = header + yaml.dump({ items: buildItemsObj() }, dumpOpts);
    // Also append recipes if they share the same file
    if (itemsFile === recipesFile && recipes.length > 0) {
      fileContent += '\n' + yaml.dump({ recipes: recipes.map(buildRecipeObj) }, dumpOpts);
    }
    result.set(itemsFile, fileContent);
  }

  // If recipes are assigned to a file that doesn't exist yet, create standalone recipes file.
  if (!result.has(recipesFile) && recipes.length > 0) {
    result.set(recipesFile, header + yaml.dump({ recipes: recipes.map(buildRecipeObj) }, dumpOpts));
  }

  // If assets are assigned to a file that doesn't exist yet, create standalone assets file.
  const assetsOut = buildAssetsObj(assets);
  if (!result.has(assetsFile) && assetsOut) {
    result.set(assetsFile, header + yaml.dump({ assets: assetsOut }, dumpOpts));
  }

  // If attributes are assigned to a standalone file that doesn't exist yet, create it.
  if (attrsFile && !result.has(attrsFile) && attrsObj) {
    result.set(attrsFile, header + yaml.dump({ attributes: attrsObj }, dumpOpts));
  }

  return result;
}

// ─── Object builders — canonical key order, falsy values omitted ──────────────

function buildMetadataObj(m) {
  const obj = {};
  if (m.title)       obj.title       = m.title;
  if (m.author)      obj.author      = m.author;
  if (m.version)     obj.version     = m.version;
  if (m.description) obj.description = m.description;
  if (m.tags?.length) obj.tags = m.tags;
  if (m.start)       obj.start       = m.start;

  // Attributes are now serialised as a top-level block (not inside metadata).
  // Kept here only for backward compat if metadata.attributes still exists.

  if (m.inventory?.length) obj.inventory = m.inventory;

  return obj;
}

function buildAttributesObj(attrs) {
  if (!attrs || Object.keys(attrs).length === 0) return null;
  const obj = {};
  for (const [name, def] of Object.entries(attrs)) {
    const entry = { value: Number(def.value ?? 0) };
    if (def.min != null) entry.min = Number(def.min);
    if (def.max != null) entry.max = Number(def.max);
    if (def.label) entry.label = def.label;
    if (def.is_hidden) entry.is_hidden = true;
    if (def.conditions?.length) {
      entry.conditions = def.conditions.map(c => {
        const condObj = { when: c.when };
        if (c.scene) condObj.scene = c.scene;
        if (c.message) condObj.message = c.message;
        return condObj;
      });
    }
    obj[name] = entry;
  }
  return obj;
}

function buildSceneObj(s) {
  const obj = {};
  if (s.title) obj.title = s.title;

  const sceneType = s.type ?? 'decision';
  // Emit type field only if non-default
  if (sceneType !== 'decision') obj.type = sceneType;

  // text: always emit for decision/through; optional for logical
  if (sceneType !== 'logical' || s.text) {
    obj.text = s.text ?? '';
  }

  // through scenes: scene-level `next` instead of choices
  if (sceneType === 'through' && s.next) {
    obj.next = s.next;
  }

  const sa = buildSceneAssetsObj(s.assets);
  if (sa) obj.assets = sa;

  const oe = buildOnEnterObj(s.on_enter);
  if (oe) obj.on_enter = oe;

  // on_revisit block
  if (s.on_revisit) {
    const rev = {};
    if (s.on_revisit.text) rev.text = s.on_revisit.text;
    if (s.on_revisit.redirect) rev.redirect = s.on_revisit.redirect;
    if (Object.keys(rev).length) obj.on_revisit = rev;
  }

  if (s.end) obj.end = true;

  // Choices: emit for decision and logical; suppress for through
  if (!s.end && sceneType !== 'through') {
    const choices = (s.choices ?? []).map(buildChoiceObj).filter(Boolean);
    if (choices.length) obj.choices = choices;
  }

  return obj;
}

function buildSceneAssetsObj(assets) {
  if (!assets || typeof assets !== 'object') return null;
  const obj = {};
  if ('image' in assets) {
    obj.image = (assets.image === null || assets.image === undefined) ? 'none' : String(assets.image);
  }
  if ('music' in assets) {
    obj.music = (assets.music === null || assets.music === undefined) ? 'none' : String(assets.music);
  }
  return Object.keys(obj).length ? obj : null;
}

function buildOnEnterObj(oe) {
  if (!oe) return null;
  const obj = {};
  if (oe.message)               obj.message       = oe.message;
  const aa = buildAffectAttributesObj(oe.affect_attributes);
  if (aa)                        obj.affect_attributes = aa;
  if (oe.gives_items?.length)   obj.gives_items   = oe.gives_items;
  if (oe.removes_items?.length) obj.removes_items = oe.removes_items;
  if (oe.gives_notes?.length)   obj.gives_notes   = oe.gives_notes;
  const sfx = serialiseGivesSfx(oe.gives_sfx);
  if (sfx !== null)              obj.gives_sfx     = sfx;
  return Object.keys(obj).length ? obj : null;
}

function buildChoiceObj(c) {
  if (!c) return null;
  const obj = {};
  if (c.label)                    obj.label          = c.label;
  if (c.next)                     obj.next           = c.next;
  // Normalise requires_item (singular) into requires_items on output
  const reqItems = buildRequiresItemsArr(c.requires_item, c.requires_items);
  if (reqItems.length)            obj.requires_items = reqItems;
  // requires_attributes: convert legacy array to dict format on output
  const reqAttrs = buildRequiresAttributesObj(c.requires_attributes);
  if (reqAttrs)                   obj.requires_attributes = reqAttrs;
  if (c.gives_items?.length)      obj.gives_items    = c.gives_items;
  if (c.removes_items?.length)    obj.removes_items  = c.removes_items;
  if (c.gives_notes?.length)      obj.gives_notes    = c.gives_notes;
  const aa = buildAffectAttributesObj(c.affect_attributes);
  if (aa)                         obj.affect_attributes = aa;
  const sfx = serialiseGivesSfx(c.gives_sfx);
  if (sfx !== null)               obj.gives_sfx      = sfx;
  return obj;
}

/**
 * Normalise requires_item (singular) and requires_items into a single array.
 * Plain string entries stay as strings; structured objects are kept as-is.
 * requires_item is merged into the array as a plain string.
 */
function buildRequiresItemsArr(requiresItem, requiresItems) {
  const out = [];
  if (requiresItem) out.push(requiresItem);
  for (const entry of requiresItems ?? []) {
    out.push(entry);
  }
  return out;
}

/**
 * Convert requires_attributes to dict format.
 * If already a dict, return as-is.
 * If legacy array [{ attr, op, value }], convert to { attr: "op value", ... }.
 * Multiple conditions on the same attribute are joined with ", ".
 */
function buildRequiresAttributesObj(attrConditions) {
  if (!attrConditions) return null;
  if (!Array.isArray(attrConditions)) {
    // Already dict format
    return Object.keys(attrConditions).length ? attrConditions : null;
  }
  // Convert legacy array to dict
  const dict = {};
  for (const cond of attrConditions) {
    const key = cond.attr;
    const part = `${cond.op} ${cond.value}`;
    if (key in dict) {
      dict[key] += `, ${part}`;
    } else {
      dict[key] = part;
    }
  }
  return Object.keys(dict).length ? dict : null;
}

function serialiseGivesSfx(sfx) {
  if (!sfx) return null;
  if (Array.isArray(sfx)) {
    if (sfx.length === 0) return null;
    return sfx.length === 1 ? sfx[0] : sfx;
  }
  return sfx; // already a string
}

function buildAssetsObj(assets) {
  if (!assets || typeof assets !== 'object') return null;
  const obj = {};
  for (const [bucket, entries] of Object.entries(assets)) {
    if (entries && typeof entries === 'object' && Object.keys(entries).length > 0) {
      obj[bucket] = { ...entries };
    }
  }
  return Object.keys(obj).length ? obj : null;
}

function buildAffectAttributesObj(aa) {
  if (!aa || typeof aa !== 'object') return null;
  const out = {};
  for (const [k, v] of Object.entries(aa)) {
    const s = String(v).trim();
    // If it's already a string with an explicit operator, keep it
    // Allow optional '-' before the digit to support "= -1" (set to negative)
    if (/^[+\-=]\s*-?\d/.test(s)) {
      // Filter out "+ 0" or "- 0" (no-op)
      const zeroMatch = s.match(/^([+\-])\s*0(?:\.0+)?$/);
      if (!zeroMatch) out[k] = s;
    } else {
      // Legacy: bare number (or FAILSAFE_SCHEMA string)
      const n = Number(v);
      if (n !== 0) out[k] = n;
    }
  }
  return Object.keys(out).length ? out : null;
}

function buildRecipeObj(r) {
  const obj = {};
  if (r.inputs?.length) obj.inputs = r.inputs;
  if (r.output)         obj.output = r.output;
  if (r.message)        obj.message = r.message;
  return obj;
}
