/**
 * serialise.js — Campaign object → YAML text per-file.
 *
 * Pure module: no DOM access. Accesses globalThis.jsyaml (same convention as
 * campaign.js — js-yaml is loaded as a non-module <script> tag).
 *
 * Single export: serialiseCampaign(campaign, originalFileMap)
 */

/**
 * Serialise a campaign object back to a map of filename → YAML text.
 *
 * metadata always goes to metadata.yaml.
 * All scenes are written to a single scenes.yaml unless the session started
 * with multiple scene files (in which case the original file assignment is
 * preserved — scenes added in Visual mode go into a new 'new_scenes.yaml').
 *
 * items: block is appended to the file that originally contained it, or to
 * scenes.yaml if no items were present on load.
 *
 * @param {{ metadata: object, scenes: object, items: object }} campaign
 * @param {Map<string, string>|null} originalFileMap  previous file map for provenance; null = single-file mode
 * @returns {Map<string, string>}  filename → YAML text
 */
export function serialiseCampaign(campaign, originalFileMap) {
  const yaml = globalThis.jsyaml;
  if (!yaml) throw new Error('js-yaml not loaded');

  const dumpOpts = { indent: 2, lineWidth: 120, schema: yaml.DEFAULT_SCHEMA };
  const header = '# Generated by Campaign Editor\n';

  const metadata = campaign.metadata ?? {};
  const scenes   = campaign.scenes   ?? {};
  const items    = campaign.items    ?? {};

  // ── 1. Serialise metadata.yaml ──────────────────────────────────────────────

  const metaObj = buildMetadataObj(metadata);
  const metaText = header + yaml.dump({ metadata: metaObj }, dumpOpts);

  // ── 2. Determine scene→file assignment ──────────────────────────────────────

  // sceneSourceFile: sceneId → filename (from original file map if available)
  const sceneSourceFile = new Map();

  if (originalFileMap && originalFileMap.size > 0) {
    for (const [filename, text] of originalFileMap) {
      if (filename === 'metadata.yaml') continue;
      // Scan for top-level scene keys under a 'scenes:' block.
      // Matches lines like "  scene_id:" (2-space indent, word chars + hyphen/underscore).
      const re = /^  ([\w][\w_-]*):/gm;
      let m;
      while ((m = re.exec(text)) !== null) {
        if (!sceneSourceFile.has(m[1])) {
          sceneSourceFile.set(m[1], filename);
        }
      }
    }
  }

  // ── 3. Determine items→file assignment ──────────────────────────────────────

  let itemsFile = 'scenes.yaml'; // default
  if (originalFileMap && originalFileMap.size > 0) {
    for (const [filename, text] of originalFileMap) {
      if (filename === 'metadata.yaml') continue;
      if (/^items:/m.test(text)) {
        itemsFile = filename;
        break;
      }
    }
  }

  // ── 4. Group scenes by output file ──────────────────────────────────────────

  // scenesByFile: filename → { sceneId: sceneData }
  const scenesByFile = new Map();

  for (const [sceneId, sceneData] of Object.entries(scenes)) {
    const file = sceneSourceFile.get(sceneId) ?? 'scenes.yaml';
    // Scenes added in Visual mode that weren't in the original file map get
    // placed into new_scenes.yaml (only when originalFileMap is non-null).
    const targetFile = (originalFileMap && originalFileMap.size > 0 && !sceneSourceFile.has(sceneId))
      ? 'new_scenes.yaml'
      : file;

    if (!scenesByFile.has(targetFile)) scenesByFile.set(targetFile, {});
    scenesByFile.get(targetFile)[sceneId] = sceneData;
  }

  // Ensure scenes.yaml always exists even if empty (so Code mode has something to show)
  if (!scenesByFile.has('scenes.yaml')) scenesByFile.set('scenes.yaml', {});

  // ── 5. Serialise each scene file ────────────────────────────────────────────

  const result = new Map();
  result.set('metadata.yaml', metaText);

  for (const [filename, fileScenes] of scenesByFile) {
    const scenesObj = {};
    for (const [sceneId, sceneData] of Object.entries(fileScenes)) {
      scenesObj[sceneId] = buildSceneObj(sceneData);
    }

    let fileContent = header;
    fileContent += yaml.dump({ scenes: scenesObj }, dumpOpts);

    // Append items block to the designated file
    if (filename === itemsFile && Object.keys(items).length > 0) {
      fileContent += '\n' + yaml.dump({ items }, dumpOpts);
    }

    result.set(filename, fileContent);
  }

  // If items are assigned to a file that had no scenes (e.g. a dedicated items.yaml),
  // create that file separately.
  if (!result.has(itemsFile) && Object.keys(items).length > 0) {
    result.set(itemsFile, header + yaml.dump({ items }, dumpOpts));
  }

  return result;
}

// ─── Object builders — canonical key order, falsy values omitted ──────────────

function buildMetadataObj(m) {
  const obj = {};
  if (m.title)       obj.title       = m.title;
  if (m.author)      obj.author      = m.author;
  if (m.version)     obj.version     = m.version;
  if (m.description) obj.description = m.description;
  if (m.tags?.length)         obj.tags  = m.tags;
  if (m.start)       obj.start       = m.start;

  const dps = m.default_player_state;
  if (dps) {
    const dpsObj = {};
    if (dps.health != null) dpsObj.health = Number(dps.health);
    if (dps.inventory?.length) dpsObj.inventory = dps.inventory;
    if (Object.keys(dpsObj).length) obj.default_player_state = dpsObj;
  }
  return obj;
}

function buildSceneObj(s) {
  const obj = {};
  if (s.title)     obj.title = s.title;
  // text is always emitted (even empty string) so scenes are valid stubs
  obj.text = s.text ?? '';

  const oe = buildOnEnterObj(s.on_enter);
  if (oe) obj.on_enter = oe;

  if (s.end) obj.end = true;

  if (!s.end) {
    const choices = (s.choices ?? []).map(buildChoiceObj).filter(Boolean);
    if (choices.length) obj.choices = choices;
  }

  return obj;
}

function buildOnEnterObj(oe) {
  if (!oe) return null;
  const obj = {};
  if (oe.message)                 obj.message       = oe.message;
  if (oe.damage && Number(oe.damage))  obj.damage  = Number(oe.damage);
  if (oe.heal   && Number(oe.heal))    obj.heal    = Number(oe.heal);
  if (oe.gives_items?.length)     obj.gives_items   = oe.gives_items;
  if (oe.removes_items?.length)   obj.removes_items = oe.removes_items;
  if (oe.gives_notes?.length)     obj.gives_notes   = oe.gives_notes;
  return Object.keys(obj).length ? obj : null;
}

function buildChoiceObj(c) {
  if (!c) return null;
  const obj = {};
  if (c.label)                    obj.label          = c.label;
  if (c.next)                     obj.next           = c.next;
  if (c.requires_item)            obj.requires_item  = c.requires_item;
  if (c.requires_items?.length)   obj.requires_items = c.requires_items;
  if (c.gives_items?.length)      obj.gives_items    = c.gives_items;
  if (c.removes_items?.length)    obj.removes_items  = c.removes_items;
  if (c.gives_notes?.length)      obj.gives_notes    = c.gives_notes;
  if (c.damage && Number(c.damage)) obj.damage       = Number(c.damage);
  if (c.heal   && Number(c.heal))   obj.heal         = Number(c.heal);
  return obj;
}
